---

boot: {}

kernel:
  name: gentoo-sources
  config:
    entries: {}
    default_entries:
      - option: EXPERT
        value:  True
      # Enable MTRR
      - option: MTRR
        value:  True
      - option: MTRR_SANITIZER
        after:  MTRR
        value:  True
      # Add support to the right init system.
      - option: GENTOO_LINUX_INIT_SCRIPT
        after:  GENTOO_LINUX
        value:  False
        enabled: "{{ systemd }}"
      - option: GENTOO_LINUX_INIT_SYSTEMD
        after:  GENTOO_LINUX_UDEV
        value:  True
        enabled: "{{ systemd }}"
      - option: FANOTIFY_ACCESS_PERMISSIONS
        value:  True
        enabled: "{{ systemd }}"
      # Add support to UEFI.
      - option: PARTITION_ADVANCED
        value:  True
        enabled: "{{ boot.uefi }}"
      - option: EFI_PARTITION
        after:  PARTITION_ADVANCED
        value:  True
        enabled: "{{ boot.uefi }}"
      - option: EFI
        value:  True
        enabled: "{{ boot.uefi }}"
      - option: EFI_STUB
        after:  EFI
        value:  True
        enabled: "{{ boot.uefi }}"
      - option: EFI_VARS
        after:  EFI
        value:  True
        enabled: "{{ boot.uefi }}"
      - option: EFI_RUNTIME_MAP
        after:  EFI
        value:  True
        enabled: "{{ boot.uefi }}"
      # HID
      - option: UHID
        after:  HID
        value:  True
      - option: HID_BATTERY_STRENGTH
        after:  HID
        value:  True
      # Device Drivers
      - option: UIO
        value:  True
      # Device Drivers - Audio
      - option: SND_HDA_INTEL
        value: True
      - option: SND_HDA_GENERIC
        after: SND_HDA_INTEL
        value: True
      - option: SND_HDA_RECONFIG
        after: SND_HDA_INTEL
        value: True
      # Device Drivers - SCSI
      - option: CHR_DEV_ST
        value:  True
      - option: SCSI_LOWLEVEL
        value:  True
      - option: SCSI_DH
        value:  True
      - option: SCSI_LOWLEVEL_PCMCIA
        value:  True
      # Device Drivers - MMC
      - option: MMC
        value:  True
      # Device Drivers - USB
      - option: USB_XHCI_HCD
        after:  USB
        value:  True
      - option: USB_UAS
        after:  USB
        value:  True
      # Device Drivers - Net
      - option: NET_VENDOR_INTEL
        value:  True
      - option: E1000E
        after:  NET_VENDOR_INTEL
        value:  True
      - option: IWLWIFI
        after:  WLAN
        value:  True
        as_module: True # Otherwise it can't load firmware from filesystem (because it gets loaded too early).
      - option: IWLMVM
        after:  IWLWIFI
        value:  True
        as_module: True
      # FUSE
      - option: FUSE_FS
        value:  True
      - option: CUSE
        after:  FUSE_FS
        value:  True
      # Systemd bootchart
      - option: DEBUG_KERNEL
        value:  True
        enabled: "{{ systemd }}"
      - option: SCHED_DEBUG
        after:  DEBUG_KERNEL
        value:  True
        enabled: "{{ systemd }}"
      - option: SCHEDSTATS
        after:  DEBUG_KERNEL
        value:  True
        enabled: "{{ systemd }}"
      # KVM
      - option: KVM
        value:  True
      - option: KVM_INTEL
        after:  KVM
        value:  True
      - option: VHOST_NET
        value:  True
      - option: NET_CORE
        value:  True
      - option: TUN
        after:  NET_CORE
        value:  True
      - option: IPV6
        value:  True
      - option: BRIDGE
        value:  True
      - option: BRIDGE_IGMP_SNOOPING
        after:  BRIDGE
        value:  True
      - option: DEBUG_FS
        value:  True
      - option: EXT4_FS
        value:  True
      - option: EXT4_FS_SECURITY
        after:  EXT4_FS
        value:  True
      # KATE-specific
      - option: HID_LENOVO
        after:  HID
        value:  True
