---

boot: {}

kernel:
  name: gentoo-sources
  config:
    entries: {}
    default_entries:
      - option: EXPERT
        value:  True
      # Enable MTRR
      - option: MTRR
        value:  True
      - option: MTRR_SANITIZER
        after:  MTRR
        value:  True
      # Add support to the right init system.
      - option: GENTOO_LINUX_INIT_SCRIPT
        after:  GENTOO_LINUX
        value:  False
        enabled: "{{ systemd }}"
      - option: GENTOO_LINUX_INIT_SYSTEMD
        after:  GENTOO_LINUX_UDEV
        value:  True
        enabled: "{{ systemd }}"
      - option: FANOTIFY_ACCESS_PERMISSIONS
        value:  True
        enabled: "{{ systemd }}"
      # Add support to UEFI.
      - option: PARTITION_ADVANCED
        value:  True
        enabled: "{{ boot.uefi }}"
      - option: EFI_PARTITION
        after:  PARTITION_ADVANCED
        value:  True
        enabled: "{{ boot.uefi }}"
      - option: EFI
        value:  True
        enabled: "{{ boot.uefi }}"
      - option: EFI_STUB
        after:  EFI
        value:  True
        enabled: "{{ boot.uefi }}"
      - option: EFI_VARS
        after:  EFI
        value:  True
        enabled: "{{ boot.uefi }}"
      - option: EFI_RUNTIME_MAP
        after:  EFI
        value:  True
        enabled: "{{ boot.uefi }}"
      # CPU
      - option: CPU_FREQ_STAT
        value:  True
      - option: CPU_FREQ_STAT_DETAILS
        after:  CPU_FREQ_STAT
        value:  True
      - option: CHECKPOINT_RESTORE
        value:  True
      # HID
      - option: UHID
        after:  HID
        value:  True
      - option: HID_BATTERY_STRENGTH
        after:  HID
        value:  True
      # Device Drivers
      - option: UIO
        value:  True
      - option: DM_THIN_PROVISIONING
        value:  True
      # Device Drivers - Audio
      - option: SND_HDA_INTEL
        value: True
      - option: SND_HDA_GENERIC
        after: SND_HDA_INTEL
        value: True
      - option: SND_HDA_RECONFIG
        after: SND_HDA_INTEL
        value: True
      # Device Drivers - SCSI
      - option: CHR_DEV_ST
        value:  True
      - option: SCSI_LOWLEVEL
        value:  True
      - option: SCSI_DH
        value:  True
      - option: SCSI_LOWLEVEL_PCMCIA
        value:  True
      # Device Drivers - MMC
      - option: MMC
        value:  True
      # Device Drivers - USB
      - option: USB_XHCI_HCD
        after:  USB
        value:  True
      - option: USB_XHCI_PLATFORM
        after:  USB_XHCI_HCD
        value:  True
      - option: USB_UAS
        after:  USB
        value:  True
      # Device Drivers - Net
      - option: MACVLAN
        value:  True
      - option: MACVTAP
        after:  MACVLAN
        value:  True
      - option: VETH
        value:  True
      - option: NET_VENDOR_INTEL
        value:  True
      - option: E1000E
        after:  NET_VENDOR_INTEL
        value:  True
      - option: IWLWIFI
        after:  WLAN
        value:  True
        as_module: True # Otherwise it can't load firmware from filesystem (because it gets loaded too early).
      - option: IWLMVM
        after:  IWLWIFI
        value:  True
        as_module: True
      # FUSE
      - option: FUSE_FS
        value:  True
      - option: CUSE
        after:  FUSE_FS
        value:  True
      # Systemd bootchart
      - option: DEBUG_KERNEL
        value:  True
        enabled: "{{ systemd }}"
      - option: SCHED_DEBUG
        after:  DEBUG_KERNEL
        value:  True
        enabled: "{{ systemd }}"
      - option: SCHEDSTATS
        after:  DEBUG_KERNEL
        value:  True
        enabled: "{{ systemd }}"
      # KVM
      - option: KVM
        value:  True
      - option: KVM_INTEL
        after:  KVM
        value:  True
      - option: VHOST_NET
        value:  True
      - option: NET_CORE
        value:  True
      - option: TUN
        after:  NET_CORE
        value:  True
      - option: IPV6
        value:  True
      - option: BRIDGE
        value:  True
      - option: BRIDGE_IGMP_SNOOPING
        after:  BRIDGE
        value:  True
      - option: DEBUG_FS
        value:  True
      - option: EXT4_FS
        value:  True
      - option: EXT4_FS_SECURITY
        after:  EXT4_FS
        value:  True
      # CGroups
      - option: CGROUP_DEVICE
        after:  CGROUP
        value:  True
      - option: CGROUP_PIDS
        after:  CGROUP
        value:  True
      - option: MEMCG
        after:  CGROUP
        value:  True
      - option: MEMCG_SWAP
        after:  MEMCG
        value:  True
      - option: MEMCG_SWAP_ENABLED
        after:  MEMCG_SWAP
        value:  True
      - option: MEMCG_KMEM
        after:  MEMCG
        value:  True
      - option: CGROUP_HUGETLB
        after:  CGROUP
        value:  True
      - option: CGROUP_PERF
        after:  CGROUP
        value:  True
      - option: CGROUP_SCHED
        after:  CGROUP
        value:  True
      - option: FAIR_GROUP_SCHED
        after:  CGROUP_SCHED
        value:  True
      - option: CFS_BANDWIDTH
        after:  FAIR_GROUP_SCHED
        value:  True
      - option: RT_GROUP_SCHED
        after:  CGROUP_SCHED
        value:  True
      - option: BLK_CGROUP
        after:  CGROUP
        value:  True
      - option: NET_CLS_CGROUP
        after:  CGROUP
        value:  True
      - option: CGROUP_NET_PRIO
        after:  CGROUP
        value:  True
      # Namespaces
      - option: UTS_NS
        after:  NAMESPACES
        value:  True
      - option: USER_NS
        after:  NAMESPACES
        value:  True
      - option: PID_NS
        after:  NAMESPACES
        value:  True
      # Netfilter
      - option: NETFILTER
        value:  True
      - option: NETFILTER_NETLINK_QUEUE
        after:  NETFILTER
        value:  True
      - option: NETFILTER_ADVANCED
        after:  NETFILTER
        value:  True
      - option: BRIDGE_NETFILTER
        after:  NETFILTER_ADVANCED
        value:  True
      - option: NF_CONNTRACK_MARK
        after:  NETFILTER
        value:  True
      - option: NETFILTER_XT_MATCH_ADDRTYPE
        after:  NETFILTER
        value:  True
      - option: NETFILTER_XT_MATCH_CONNTRACK
        after:  NETFILTER
        value:  True
      - option: NF_NAT_IPV4
        after:  NETFILTER
        value:  True
      - option: NF_NAT_MASQUERADE_IPV4
        after:  NETFILTER
        value:  True
      - option: IP_NF_IPTABLES
        after:  NETFILTER
        value:  True
      - option: IP_NF_NAT
        after:  NETFILTER
        value:  True
      - option: IP_NF_TARGET_MASQUERADE
        after:  NETFILTER
        value:  True
      - option: IP_NF_TARGET_NETMAP
        after:  NETFILTER
        value:  True
      - option: IP_NF_TARGET_REDIRECT
        after:  NETFILTER
        value:  True
      # Filesystem
      - option: OVERLAY_FS
        value:  True
      - option: HUGETLBFS
        value:  True
      # Security
      - option: PERSISTENT_KEYRINGS
        value: True
      - option: ENCRYPTED_KEYS
        value: True
        as_module: True
      # PPTP
      - option: PPP
        value:  True
      - option: PPP_BSDCOMP
        value:  True
      - option: PPP_DEFLATE
        value:  True
      - option: PPP_FILTER
        value:  True
      - option: PPP_MPPE
        value:  True
      - option: PPP_MULTILINK
        value:  True
      - option: PPPOE
        value:  True
      - option: PPP_ASYNC
        value:  True
      - option: PPP_SYNC_TTY
        value:  True
      # KATE-specific
      - option: HID_LENOVO
        after:  HID
        value:  True
