---

boot: {}

kernel:
  name: gentoo-sources
  config:
    entries: {}
    default_entries:
      - option: EXPERT
        value:  True
      # Enable MTRR
      - option: MTRR
        value:  True
      - option: MTRR_SANITIZER
        after:  MTRR
        value:  True
      # Add support to the right init system.
      - option: GENTOO_LINUX_INIT_SCRIPT
        after:  GENTOO_LINUX
        value:  False
        enabled: "{{ systemd }}"
      - option: GENTOO_LINUX_INIT_SYSTEMD
        after:  GENTOO_LINUX_UDEV
        value:  True
        enabled: "{{ systemd }}"
      - option: FANOTIFY_ACCESS_PERMISSIONS
        value:  True
        enabled: "{{ systemd }}"
      # Add support to UEFI.
      - option: PARTITION_ADVANCED
        value:  True
        enabled: "{{ boot.uefi }}"
      - option: EFI_PARTITION
        after:  PARTITION_ADVANCED
        value:  True
        enabled: "{{ boot.uefi }}"
      - option: EFI
        value:  True
        enabled: "{{ boot.uefi }}"
      - option: EFI_STUB
        after:  EFI
        value:  True
        enabled: "{{ boot.uefi }}"
      - option: EFI_VARS
        after:  EFI
        value:  True
        enabled: "{{ boot.uefi }}"
      - option: EFI_RUNTIME_MAP
        after:  EFI
        value:  True
        enabled: "{{ boot.uefi }}"
      # Device Drivers
      - option: NET_VENDOR_INTEL
        value:  True
      - option: E1000E
        after:  NET_VENDOR_INTEL
        value:  True
      - option: IWLWIFI
        after:  WLAN
        value:  True
        as_module: True # Otherwise it can't load firmware from filesystem (because it gets loaded too early).
      - option: IWLMVM
        after:  IWLWIFI
        value:  True
        as_module: True
      - option: FB_NVIDIA
        value: True
      - option: FB_NVIDIA_I2C
        after:  FB_NVIDIA
        as_module: True # Otherwise it goes in kernel panic.
        value:  True
      - option: FB_NVIDIA_BACKLIGHT
        after:  FB_NVIDIA
        value:  True
      # FUSE
      - option: FUSE_FS
        value:  True
      - option: CUSE
        after:  FUSE_FS
        value:  True
      # Systemd bootchart
      - option: DEBUG_KERNEL
        value:  True
        enabled: "{{ systemd }}"
      - option: SCHED_DEBUG
        after:  DEBUG_KERNEL
        value:  True
        enabled: "{{ systemd }}"
      - option: SCHEDSTATS
        after:  DEBUG_KERNEL
        value:  True
        enabled: "{{ systemd }}"
      # KVM
      - option: KVM
        value:  True
      - option: KVM_INTEL
        after:  KVM
        value:  True
      - option: VHOST_NET
        value:  True
      - option: NET_CORE
        value:  True
      - option: TUN
        after:  NET_CORE
        value:  True
      - option: IPV6
        value:  True
      - option: BRIDGE
        value:  True
      - option: BRIDGE_IGMP_SNOOPING
        after:  BRIDGE
        value:  True
      - option: DEBUG_FS
        value:  True
      - option: EXT4_FS
        value:  True
      - option: EXT4_FS_SECURITY
        after:  EXT4_FS
        value:  True
