---
# Used tags:
# - service: to enable and manage services
# - profile: to setup the profile
# - sync: to sync portage repositories
# - repository: to setup repository
# - install: to install packages
# - configure_system: to perform system-level configuration
# - configure_user: to perform user-level configuration

- include: setup_users.yml
- include: setup_system.yml
- include: setup_portage.yml
- include: setup_x11.yml
- include: setup_fonts.yml

- follow backup.md in configs_book

