---

fizzy cfg s -C xorg -U ssh:alem0lars/configs-xorg
fizzy qi -C xorg -I xorg -V kate

- name: Install X11 software
  portage:
    package: "{{ item }}"
    state:   installed
    update:  "yes"
  with_items: "{{ packages.x11 }}"
  tags: install

- command: localectl set-x11-keymap us pc105+inet "" terminate:ctrl_alt_bksp,ctrl:nocaps

- name: Setup display manager (1/3 Install)
  portage:
    package: "{{ packages |
                 attr(display_manager) }}"
    state:   installed
    update:  "yes"
  tags: install

- name: Setup display manager (2/3 Enable)
  command: "{{ 'systemctl enable %s' |
               format(display_manager) }}"
  tags: service

fizzy cfg s -C lightdm -U ssh:alem0lars/configs-lightdm
fizzy qi -C lightdm -I lightdm -V kate

- name: Setup window manager (1/2 Install)
  portage:
    package: "{{ packages[window_manager] }}"
    state:   installed
    update:  "yes"
  tags: install

- name: Setup window manager (2/2 Configure)
  template:
    src:  "{{ window_manager }}/xmonad.hs.j2"
    dest: ~/.xmonad/xmonad.hs
  when: "{{ window_manager == 'xmonad' }}"
  tags: configure_user
