---

- command: systemd-machine-id-setup
  when: "{{ systemd is defined }}"
  tags: service

mettere in /etc/locale.gen
  en_US.UTF-8 UTF-8

- command: locale-gen

- command: localectl set-locale LANG=en_US.utf8
  when: "{{ systemd is defined }}"
  tags: service

- command: localectl set-keymap us
  when: "{{ systemd is defined }}"
  tags: service

- command: timedatectl set-ntp true
  when: "{{ systemd is defined }}"
  tags: service

- command: timedatectl set-timezone Europe/Rome
  when: "{{ systemd is defined }}"
  tags: service

- command: systemctl enable systemd-networkd
  when: "{{ systemd is defined }}"
  tags: service

- command: systemctl enable systemd-resolved 
  when: "{{ systemd is defined }}"
  tags: service

- command: systemctl enable avahi-daemon
  when: "{{ systemd is defined }}"
  tags: service

- command: # TODO: Add wired.network config file
  when: "{{ systemd is defined }}"
  tags: service

- command: systemctl restart systemd-networkd
  when: "{{ systemd is defined }}"
  tags: service

- command: systemctl restart systemd-resolved 
  when: "{{ systemd is defined }}"
  tags: service

- command: # TODO: Add /etc/nsswitch.conf config file
  when: "{{ systemd is defined }}"
  tags: service
  # files mdns4_minimal [NOTFOUND=return] dns mdns4

- command: emerge net-dns/avahi sys-auth/nss-mdns

- command: systemctl restart avahi-daemon
  when: "{{ systemd is defined }}"
  tags: service
  
- command: ln -sf /run/systemd/resolve/resolv.conf /etc/resolv.conf
  when: "{{ systemd is defined }}"
  tags: service

- command: hostnamectl set-hostname kate # TODO: replace with customized value
  when: "{{ systemd is defined }}"
  tags: service

- command: hostnamectl set-chassis laptop # TODO: replace with customized value
  when: "{{ systemd is defined }}"
  tags: service

- command: hostnamectl set-deployment production # TODO: replace with customized value
  when: "{{ systemd is defined }}"
  tags: service

- name: Update packages
  portage:
    package: "@world"
    update:  "yes"
    deep:    "yes"
    sync:    "yes"
  tags: sync

- name: Setup local portage repository (1/4)
  file:
    path:  /usr/local/portage/metadata
    state: directory
  tags: repository

- name: Setup local portage repository (2/4)
  template:
    src:  portage/local_repository/layout.conf.j2
    dest: /usr/local/portage/metadata/layout.conf
  tags: repository

- name: Setup local portage repository (3/4)
  template:
    src:  portage/local_repository/repo_name.j2
    dest: /usr/local/portage/repo_name
  tags: repository

- name: Setup local portage repository (4/4)
  command: chown -R portage:portage /usr/local/portage
  tags: repository

# Crossdev
# root #mkdir -p /usr/local/portage-crossdev/{profiles,metadata}
# root #echo 'crossdev' > /usr/local/portage-crossdev/profiles/repo_name
# root #echo 'masters = gentoo' > /usr/local/portage-crossdev/metadata/layout.conf
# root #chown -R portage:portage /usr/local/portage-crossdev
# If the main Portage tree is synchronized by using Git, or any other method with Manifest files that do not include checksums for ebuilds, prevent "masked by: corruption" errors with:

# FILE /usr/local/portage-crossdev/metadata/layout.conf
# masters = gentoo
# thin-manifests = true
# Then instruct Portage and crossdev to use this overlay:

# FILE /etc/portage/repos.conf/crossdev.conf
# [crossdev]
# location = /usr/local/portage-crossdev
# priority = 10
# masters = gentoo
# auto-sync = no

- name: Install basic software
  portage:
    package: "{{ item }}"
    state:   installed
    update:  "yes"
  with_items: "{{ packages.basic }}"
  tags: install


- command: systemctl enable systemd-bootchart

