# NeoVim

sudo emerge "app-editors/nvim"

Set default editor:

eselect editor list # Shows the available editors.
eselect editor set "/usr/bin/nvim" # Set the system editor
source /etc/profile

sudo fizzy cfg s -C vim -U ssh:alem0lars/configs-vim
sudo fizzy qi -C vim -I vim -V kate

# Etherpad Lite

sudo emerge "www-apps/etherpad-lite"
