---

fizzy cfg s -C dracut -U ssh:alem0lars/configs-dracut
fizzy qi -C dracut -I dracut -V kate

- command: systemd-machine-id-setup
  when: "{{ systemd is defined }}"
  tags: service

mettere in /etc/locale.gen
  en_US.UTF-8 UTF-8

- command: locale-gen

- command: localectl set-locale LANG=en_US.utf8
  when: "{{ systemd is defined }}"
  tags: service

- command: localectl set-keymap us
  when: "{{ systemd is defined }}"
  tags: service

- command: timedatectl set-ntp true
  when: "{{ systemd is defined }}"
  tags: service

- command: timedatectl set-timezone Europe/Rome
  when: "{{ systemd is defined }}"
  tags: service

fizzy cfg s -C systemd -U ssh:alem0lars/configs-systemd
fizzy qi -C systemd -I systemd -V kate

- command: systemctl enable systemd-networkd
  when: "{{ systemd is defined }}"
  tags: service

sudo emerge dnsmasq

sudo systemctl restart dnsmasq

- command: systemctl enable systemd-resolved
  when: "{{ systemd is defined }}"
  tags: service

- command: systemctl restart systemd-networkd
  when: "{{ systemd is defined }}"
  tags: service

# Wireless
fizzy cfg s -C wpa -U ssh:alem0lars/configs-wpa
fizzy qi -C wpa -I wpa -V kate
systemctl enable wpa_supplicant@wlp3s0
systemctl start wpa_supplicant@wlp3s0

- command: # TODO: Add /etc/nsswitch.conf config file
  when: "{{ systemd is defined }}"
  tags: service
  # files mdns4_minimal [NOTFOUND=return] dns mdns4

- command: emerge net-dns/avahi sys-auth/nss-mdns
- command: systemctl enable avahi-daemon
  when: "{{ systemd is defined }}"
  tags: service
- command: systemctl restart avahi-daemon
  when: "{{ systemd is defined }}"
  tags: service

- command: ln -sf /run/systemd/resolve/resolv.conf /etc/resolv.conf
  when: "{{ systemd is defined }}"
  tags: service

- command: hostnamectl set-hostname kate # TODO: replace with customized value
  when: "{{ systemd is defined }}"
  tags: service

- command: hostnamectl set-chassis laptop # TODO: replace with customized value
  when: "{{ systemd is defined }}"
  tags: service

- command: hostnamectl set-deployment production # TODO: replace with customized value
  when: "{{ systemd is defined }}"
  tags: service

- command: systemctl enable systemd-bootchart
