---

# TODO: fix file

# Cosi' funziona per local e gentoo
- name: Setup repos.conf
  template:
    src:   /repos/gentoo.conf.j2
    dest:  /etc/portage/repos.conf/gentoo.conf

- name: Setup repos.conf
  template:
    src:   /repos/local.conf
    dest:  /etc/portage/repos.conf/local.conf

- name: Update GCC version
 command: gcc-config 1 # TODO: Choose based on CHOST

- name: Update environment
  command: eselect env update
  tags:
    - environment

# Aggiungere l'utente
- command: useradd -m -G -s /bin/bash alem0lars

- name: fare passi di alem0lars/configs_book/gentoo/configuration/software/portage.md


# ------------------------------------------------------------------------------------

# TODO: check se son buoni: eclean-kernel diffmask flaggie install-mask portpeek smart-live-rebuild
# e in tal caso aggiungerli

- command: layman -o https://raw.github.com/alem0lars/apo/master/repositories.xml -f -a apo