- name: Install Portage
  command: "{{ '/usr/bin/emerge-webrsync' |
               chrooted('/mnt/gentoo') }}"

- name: Select profile
  eselect_profile:
    arch:      "{{ arch                      }}"
    multilib:  "{{ multilib  | default(omit) }}"
    hardened:  "{{ hardened  | default(omit) }}"
    systemd:   "{{ systemd   | default(omit) }}"
    selinux:   "{{ selinux   | default(omit) }}"
    developer: "{{ developer | default(omit) }}"
    desktop:   "{{ desktop   | default(omit) }}"
    chroot: /mnt/gentoo

- name: Sync repository
  command: "{{ 'emerge --sync' |
               chrooted('/mnt/gentoo') }}"

- name: Fix udev version
  command: "{{ 'emerge --deselect=y sys-fs/eudev' |
               chrooted('/mnt/gentoo') }}"
  when: "{{ systemd }}"

- name: Unmask some packages
  lineinfile:
    dest: /mnt/gentoo/etc/portage/package.keywords/temporary
    line: "sys-kernel/dracut"
    create: yes

- name: Enable some common USE flags required later
  lineinfile:
    dest: /mnt/gentoo/etc/portage/make.conf
    line: "USE=\"$USE
      cryptsetup
      elfutils
      gnuefi
      {{ (boot.uefi and boot.kind == 'systemd') | ternary('gnuefi', omit) }}\""

- name: Disable parallel compiling
  lineinfile:
    dest: /mnt/gentoo/etc/portage/make.conf
    line: MAKEOPTS=-j1

- name: Update packages (1/4)
  lineinfile:
    dest: /mnt/gentoo/etc/portage/package.use/temporary
    line: "sys-apps/systemd -cryptsetup -gnuefi"
    create: yes

- name: Update packages (2/4)
  command: "{{ 'emerge --update --newuse --deep --with-bdeps=y @system @world' |
               chrooted('/mnt/gentoo') }}"

- name: Update packages (3/4)
  lineinfile:
    dest: /mnt/gentoo/etc/portage/package.use/temporary
    line: "sys-apps/systemd -cryptsetup -gnuefi"
    create: yes
    state: absent

- name: Update packages (4/4)
  command: "{{ 'emerge --update --newuse --deep --with-bdeps=y @system @world' |
               chrooted('/mnt/gentoo') }}"
